# Base de datos en RDS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Inicialización de SQL
spring.sql.init.mode=never

# Servidor Frontend (producción)
servidor.frontend=https://worklog.rustikas.com.uy
